server:
  port: 8081

spring:
  application:
    name: supermarket-api
  main:
    allow-circular-references: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: admin
    password: admin
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5434/supermarket-db
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none  # Choose to 'update' or 'create-drop' if you're developing but 'none' to production
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always  # You can use 'never' in production too

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
